{{- if and .Values.global.serviceAccount.create .Values.global.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.serviceAccountName" . }}
  labels:
{{ include "thanos.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.global.serviceAccount.annotations | indent 4 }}
{{- end }}
