{{- if and .Values.query.enabled .Values.query.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "thanos.compName" (list . "query") }}
  labels:
{{ include "thanos.labels" . | indent 4 }}
  annotations:
    {{- include "thanos.annotations" (dict "Values" .Values "component" "query") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.query.autoscaling.targetKind | default "Deployment" }}
    name: {{ include "thanos.compName" (list . "query") }}
  minReplicas: {{ .Values.query.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.query.autoscaling.maxReplicas }}
  metrics:
  {{- $cpu := .Values.query.autoscaling.targetCPUUtilizationPercentage }}
  {{- $mem := .Values.query.autoscaling.targetMemoryUtilizationPercentage }}
  {{- if or $cpu $mem }}
    {{- if $cpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $cpu }}
    {{- end }}
    {{- if $mem }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $mem }}
    {{- end }}
  {{- else }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  {{- end }}
{{- end }}
